# Generated by Django 5.2.3 on 2025-06-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++')], max_length=255),
        ),
    ]
