# Generated by Django 5.2.3 on 2025-06-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_alter_snippet_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['-created_at']},
        ),
    ]
