# Generated by Django 5.2.3 on 2025-07-01 13:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_alter_snippet_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.snippet')),
            ],
        ),
    ]
