# Generated by Django 5.2.4 on 2025-07-31 04:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(choices=[('PYTHON', 'Python'), ('JAVASCRIPT', 'JavaScript'), ('HTML', 'HTML'), ('CSS', 'CSS')], max_length=255, unique=True),
        ),
    ]
