# Generated by Django 5.2.4 on 2025-07-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_customuser_created_at_customuser_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(choices=[('PYTHON', 'Python'), ('JAVASCRIPT', 'JavaScript'), ('HTML', 'HTML'), ('CSS', 'CSS')], max_length=255),
        ),
    ]
