# Generated by Django 5.2.4 on 2025-08-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0005_alter_comment_options_like'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_snippet_title ON orm_snippet (title);",
            reverse_sql="DROP INDEX IF EXISTS idx_snippet_title;",
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_snippet_description ON orm_snippet (description);",
            reverse_sql="DROP INDEX IF EXISTS idx_snippet_description;",
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_snippet_language ON orm_snippet (language);",
            reverse_sql="DROP INDEX IF EXISTS idx_snippet_language;",
        ),
    ]
