# Generated by Django 5.2.4 on 2025-08-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0008_customuser_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='snippet',
            options={},
        ),
        migrations.RenameField(
            model_name='sharedsnippet',
            old_name='created_by',
            new_name='shared_by',
        ),
    ]
